spring:
  application:
    name: eureka-server
---
spring:
  profiles: peer1
server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: peer1
    password: admin
eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762
security:
  basic:
    enabled: true
  user:
    name: peer2
    password: admin
eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/

